server:
  port: 9013
spring:
  application:
    name: api-gateway
# Package service route
  cloud:
    gateway:
      routes[0]:
        id: package-service
        uri: lb://package-service
        predicates[0]:
          Path: /packages
#Tourism service route
      routes[1]:
        id: tourism-service
        uri: lb://tourism-service
        predicates[0]:
          Path: /tourism/api/v1/branch/**
  #Discovery service route
      routes[2]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]:
          Path: /eureka/web
        filters[0]:
          SetPath: /
  #Discovery service static route to load css, script and other resources
      routes[3]:
        id: discovery-service-static
        uri: http://localhost:8761
        predicates[0]:
          Path: /eureka/**